server:
  port: 8081

spring:
  datasource:
    username: root
    password: 15290682086
    url: jdbc:mysql://localhost:3306/springboot_mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
